import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  infraSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: false,
      items: [
        'intro',
        'getting-started/what-is-safrochain',
        'getting-started/quick-links',
        {
          type: 'link',
          label: 'Ask me',
          href: '/chat',
        },
      ],
    },
    {
      type: 'category',
      label: 'Networks',
      collapsed: false,
      items: [
        'networks/mainnet-endpoints',
        'networks/testnet-endpoints',
        'networks/local-devnet-endpoints',
        'networks/chain-registry',
      ],
    },
    {
      type: 'category',
      label: 'Run a Node',
      collapsed: true,
      items: [
        'run-a-node/overview',
        'run-a-node/install',
        'run-a-node/hardware',
        'run-a-node/local-devnet',
        'run-a-node/local-testnet',
        'run-a-node/join-testnet',
        'run-a-node/join-mainnet',
        'run-a-node/snapshots',
        'run-a-node/statesync',
        'run-a-node/upgrades',
      ],
    },
    {
      type: 'category',
      label: 'Validators',
      collapsed: true,
      link: { type: 'doc', id: 'validators/overview' },
      items: [
        'validators/overview',
        'validators/become-a-validator',
        {
          type: 'category',
          label: 'Keys & signing',
          collapsed: true,
          items: [
            'validators/key-management',
            'validators/remote-signing',
          ],
        },
        'validators/sentry-architecture',
        {
          type: 'category',
          label: 'Monitoring & alerting',
          collapsed: true,
          items: [
            'validators/monitoring',
            'validators/alerting',
          ],
        },
        'validators/operations',
        'validators/security',
        'validators/disaster-recovery',
        'validators/slashing',
      ],
    },
    {
      type: 'category',
      label: 'IBC & Relayers',
      collapsed: true,
      items: ['ibc/overview', 'ibc/hermes-setup', 'ibc/channels'],
    },
    {
      type: 'category',
      label: 'CLI Reference',
      collapsed: true,
      items: [
        'cli/overview',
        'cli/keys',
        'cli/bank',
        'cli/staking',
        'cli/governance',
        'cli/query',
        'cli/tx',
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      collapsed: true,
      link: { type: 'doc', id: 'modules/overview' },
      items: [
        'modules/overview',
        {
          type: 'category',
          label: 'Safrochain modules',
          collapsed: true,
          items: [
            'modules/tokenfactory',
            'modules/globalfee',
            'modules/feepay',
            'modules/feeshare',
            'modules/drip',
            'modules/clock',
            'modules/cw-hooks',
          ],
        },
        {
          type: 'category',
          label: 'Cosmos SDK',
          collapsed: true,
          items: [
            'modules/auth',
            'modules/bank',
            'modules/staking',
            'modules/gov',
            'modules/mint',
            'modules/slashing',
            'modules/distribution',
            'modules/evidence',
            'modules/feegrant',
            'modules/authz',
            'modules/nft',
            'modules/consensus',
            'modules/params',
            'modules/upgrade',
            'modules/crisis',
            'modules/vesting',
          ],
        },
        {
          type: 'category',
          label: 'IBC',
          collapsed: true,
          items: [
            'modules/ibc-core',
            'modules/ibc-transfer-app',
            'modules/ibc-fee',
            'modules/interchain-accounts',
            'modules/interchain-query',
            'modules/ibc-hooks',
          ],
        },
        {
          type: 'category',
          label: 'CosmWasm',
          collapsed: true,
          items: ['modules/wasm'],
        },
      ],
    },
    {
      type: 'category',
      label: 'About',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Protocol',
          collapsed: true,
          items: [
            'protocol/tokenomics',
            'protocol/governance',
            'protocol/foundation',
          ],
        },
        {
          type: 'category',
          label: 'Resources',
          collapsed: true,
          items: [
            'resources/whitepaper',
            'resources/brand-assets',
            'resources/faq',
          ],
        },
      ],
    },
  ],
  developersSidebar: [
    'developers/start-here',
    {
      type: 'category',
      label: 'Get Started',
      collapsed: false,
      link: { type: 'doc', id: 'developers/get-started/choose-your-stack' },
      items: [
        'developers/get-started/choose-your-stack',
        'developers/get-started/testnet-setup',
        'developers/get-started/local-devnet',
        'developers/get-started/first-transaction',
      ],
    },
    {
      type: 'category',
      label: 'Mobile',
      collapsed: true,
      items: [
        'developers/mobile/flutter',
        'developers/mobile/react-native',
        'developers/mobile/keys-and-ux',
      ],
    },
    {
      type: 'category',
      label: 'SafHandle',
      collapsed: true,
      link: { type: 'doc', id: 'developers/safhandle/index' },
      items: [
        'developers/safhandle/index',
        'developers/safhandle/resolve',
        'developers/safhandle/register',
        'developers/safhandle/manage',
      ],
    },
    {
      type: 'category',
      label: 'Wallets',
      collapsed: true,
      link: { type: 'doc', id: 'developers/wallets/supported-wallets' },
      items: [
        'developers/wallets/supported-wallets',
        'developers/wallets/cosmos-kit',
        'developers/wallets/connect-browser-wallets',
      ],
    },
    {
      type: 'category',
      label: 'Transactions',
      collapsed: true,
      link: { type: 'doc', id: 'developers/transactions/signing-overview' },
      items: [
        'developers/transactions/signing-overview',
        'developers/transactions/simulate-gas-fees',
        'developers/transactions/broadcast-modes',
      ],
    },
    {
      type: 'category',
      label: 'Smart Contracts',
      collapsed: true,
      link: { type: 'doc', id: 'developers/smart-contracts/overview' },
      items: [
        'developers/smart-contracts/overview',
        'developers/smart-contracts/build-in-rust',
        'developers/smart-contracts/deploy-and-manage',
        'developers/smart-contracts/interact-from-apps',
        'developers/smart-contracts/local-dev-and-testing',
      ],
    },
    {
      type: 'category',
      label: 'Web and TypeScript',
      collapsed: true,
      items: [
        'developers/web/cosmjs',
        'developers/web/query-chain',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: true,
      items: [
        'developers/integrations/ibc-transfers',
        'developers/integrations/payments-flow',
        'developers/integrations/token-factory',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        'developers/reference/chain-constants',
        'developers/reference/endpoints',
        'developers/reference/events-and-websockets',
      ],
    },
  ],
};

export default sidebars;
